sm_id = "dock"
states = ["DOCK"]
outcomes = ["DONE", "FAILED"]

[state_descriptions]
    [state_descriptions.DOCK]
        state_module_name = "ropod_experiment_executor.commands.dock"
        state_class_name = "Dock"
        initial_state = true
        [state_descriptions.DOCK.transitions]
            done = "DONE"
            failed = "FAILED"
        [state_descriptions.DOCK.arguments]
            area_id = "MobidikArea1"
            area_name = "orient_wp_MobidikArea1"
            dock_action_topic = "/ropod_task_executor/DOCK"
            dock_progress_topic = "/task_progress/dock"
            timeout_s = 120.0
