sm_id = "elevator_navigation"
states = ["ENTER_ELEVATOR", "RIDE_ELEVATOR", "EXIT_ELEVATOR"]
outcomes = ["DONE", "FAILED"]

[state_descriptions]
    [state_descriptions.ENTER_ELEVATOR]
        state_module_name = "ropod_experiment_executor.commands.enter_elevator"
        state_class_name = "EnterElevator"
        initial_state = true
        [state_descriptions.ENTER_ELEVATOR.transitions]
            done = "RIDE_ELEVATOR"
            failed = "FAILED"
        [state_descriptions.ENTER_ELEVATOR.arguments]
            area_floor = 0
            elevator_id = 121
            elevator_door_id = 196
            timeout_s = 120.0
    [state_descriptions.RIDE_ELEVATOR]
        state_module_name = "ropod_experiment_executor.commands.ride_elevator"
        state_class_name = "RideElevator"
        [state_descriptions.RIDE_ELEVATOR.transitions]
            done = "EXIT_ELEVATOR"
            failed = "FAILED"
        [state_descriptions.RIDE_ELEVATOR.arguments]
            destination_floor = 2
            timeout_s = 600.0
    [state_descriptions.EXIT_ELEVATOR]
        state_module_name = "ropod_experiment_executor.commands.exit_elevator"
        state_class_name = "ExitElevator"
        [state_descriptions.EXIT_ELEVATOR.transitions]
            done = "DONE"
            failed = "FAILED"
        [state_descriptions.EXIT_ELEVATOR.arguments]
            outside_area_id = 158
            outside_area_name = 'BRSU_A_L2_C1_LA2'
            timeout_s = 120.0

[arguments]
    elevator_action_server_name = "/ropod/take_elevator"
    elevator_progress_topic = "/ropod/take_elevator/feedback"
