# Description: Defines a state machine for a simple in-place rotational motion of a robot (right, left)
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: in_place_rotation
states: [ROTATE_RIGHT, ROTATE_LEFT]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: ROTATE_RIGHT
        state_module_name: ropod_experiment_executor.commands.base_motion
        state_class_name: BaseMotion
        transitions:
            - transition:
                name: done
                state: ROTATE_LEFT
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: vel_x
                value: 0.0
            - argument:
                name: vel_y
                value: 0.0
            - argument:
                name: vel_theta
                value: 0.2
            - argument:
                name: duration
                value: 3.0
            - argument:
                name: vel_topic
                value: /ropod/cmd_vel
    - state:
        name: ROTATE_LEFT
        state_module_name: ropod_experiment_executor.commands.base_motion
        state_class_name: BaseMotion
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: vel_x
                value: 0.0
            - argument:
                name: vel_y
                value: 0.0
            - argument:
                name: vel_theta
                value: -0.2
            - argument:
                name: duration
                value: 3.0
            - argument:
                name: vel_topic
                value: /ropod/cmd_vel
