# Description: Defines a state machine for a simple linear motion of a robot (straight, left, right)
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: linear_motion
states: [GO_FORWARD, GO_RIGHT, GO_BACKWARD, GO_LEFT]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: GO_FORWARD
        state_module_name: ropod_experiment_executor.commands.base_motion
        state_class_name: BaseMotion
        transitions:
            - transition:
                name: done
                state: GO_RIGHT
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: vel_x
                value: 0.2
            - argument:
                name: vel_y
                value: 0.0
            - argument:
                name: vel_theta
                value: 0.0
            - argument:
                name: duration
                value: 3.0
            - argument:
                name: vel_topic
                value: /ropod/cmd_vel
    - state:
        name: GO_RIGHT
        state_module_name: ropod_experiment_executor.commands.base_motion
        state_class_name: BaseMotion
        transitions:
            - transition:
                name: done
                state: GO_BACKWARD
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: vel_x
                value: 0.0
            - argument:
                name: vel_y
                value: -0.2
            - argument:
                name: vel_theta
                value: 0.0
            - argument:
                name: duration
                value: 3.0
            - argument:
                name: vel_topic
                value: /ropod/cmd_vel
    - state:
        name: GO_BACKWARD
        state_module_name: ropod_experiment_executor.commands.base_motion
        state_class_name: BaseMotion
        transitions:
            - transition:
                name: done
                state: GO_LEFT
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: vel_x
                value: -0.2
            - argument:
                name: vel_y
                value: 0.0
            - argument:
                name: vel_theta
                value: 0.0
            - argument:
                name: duration
                value: 3.0
            - argument:
                name: vel_topic
                value: /ropod/cmd_vel
    - state:
        name: GO_LEFT
        state_module_name: ropod_experiment_executor.commands.base_motion
        state_class_name: BaseMotion
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: vel_x
                value: 0.0
            - argument:
                name: vel_y
                value: 0.2
            - argument:
                name: vel_theta
                value: 0.0
            - argument:
                name: duration
                value: 3.0
            - argument:
                name: vel_topic
                value: /ropod/cmd_vel
