sm_id = "nav_dock_undock"
states = ["GET_PATH_PLAN_TO_DOCKING_STATION", "GO_TO_DOCKING_STATION", "DOCK", "GET_PATH_PLAN_TO_ELEVATOR", "GO_TO_ELEVATOR", "ENTER_ELEVATOR"]
outcomes = ["DONE", "FAILED"]

[state_descriptions]
    [state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION]
        state_module_name = "ropod_experiment_executor.commands.get_path_plan"
        state_class_name = "GetPathPlan"
        initial_state = true
        [state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.transitions]
            done = "GO_TO_DOCKING_STATION"
            failed = "FAILED"
        [state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments]
            use_planner = false
            area_floor = 0
            [[state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments.areas]]
                area_id = "5"
                area_name = "BRSU_C_L0_C9"
                area_type = "corridor"
                subarea_id = "61"
                subarea_name = "BRSU_C_L0_C9_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments.areas]]
                area_id = "7"
                area_name = "BRSU_C_L0_C8"
                area_type = "junction"
                subarea_id = "64"
                subarea_name = "BRSU_C_L0_C8_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments.areas]]
                area_id = "2"
                area_name = "BRSU_C_L0_C11"
                area_type = "corridor"
                subarea_id = "57"
                subarea_name = "BRSU_C_L0_C11_LA2"
    [state_descriptions.GO_TO_DOCKING_STATION]
        state_module_name = "ropod_experiment_executor.commands.goto"
        state_class_name = "GoTo"
        [state_descriptions.GO_TO_DOCKING_STATION.transitions]
            done = "DOCK"
            failed = "FAILED"
        [state_descriptions.GO_TO_DOCKING_STATION.arguments]
            timeout_s = 1200.0
    [state_descriptions.DOCK]
        state_module_name = "ropod_experiment_executor.commands.dock"
        state_class_name = "Dock"
        [state_descriptions.DOCK.transitions]
            done = "GET_PATH_PLAN_TO_ELEVATOR"
            failed = "FAILED"
        [state_descriptions.DOCK.arguments]
            area_id = "2"
            area_name = "BRSU_C_L0_C11"
            sub_area_id = "56"
            sub_area_name = "BRSU_C_L0_C11_LA1"
            dock_action_server_name = "/collect_cart"
            dock_progress_topic = "/collect_cart/feedback"
            timeout_s = 120.0
    [state_descriptions.GET_PATH_PLAN_TO_ELEVATOR]
        state_module_name = "ropod_experiment_executor.commands.get_path_plan"
        state_class_name = "GetPathPlan"
        [state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.transitions]
            done = "GO_TO_ELEVATOR"
            failed = "FAILED"
        [state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments]
            use_planner = false
            area_floor = 0
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "2"
                area_name = "BRSU_C_L0_C11"
                area_type = "corridor"
                subarea_id = "56"
                subarea_name = "BRSU_C_L0_C11_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "7"
                area_name = "BRSU_C_L0_C8"
                area_type = "junction"
                subarea_id = "64"
                subarea_name = "BRSU_C_L0_C8_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "92"
                area_name = "BRSU_C_L0_C7"
                area_type = "corridor"
                subarea_id = "66"
                subarea_name = "BRSU_C_L0_C7_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "8"
                area_name = "BRSU_C_L0_C6"
                area_type = "corridor"
                subarea_id = "68"
                subarea_name = "BRSU_C_L0_C6_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "9"
                area_name = "BRSU_C_L0_C5"
                area_type = "corridor"
                subarea_id = "70"
                subarea_name = "BRSU_C_L0_C5_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "10"
                area_name = "BRSU_C_L0_C4"
                area_type = "corridor"
                subarea_id = "72"
                subarea_name = "BRSU_C_L0_C4_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "12"
                area_name = "BRSU_C_L0_C2"
                area_type = "junction"
                subarea_id = "75"
                subarea_name = "BRSU_C_L0_C2_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "13"
                area_name = "BRSU_C_L0_C2"
                area_type = "corridor"
                subarea_id = "76"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "123"
                area_name = "BRSU_C_L0_C2"
                area_type = "area"
                subarea_id = "117"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "124"
                area_name = "BRSU_C_L0_C2"
                area_type = "area"
                subarea_id = "118"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "126"
                area_name = "BRSU_C_L0_C2"
                area_type = "area"
                subarea_id = "119"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_ELEVATOR.arguments.areas]]
                area_id = "125"
                area_name = "BRSU_C_L0_C2"
                area_type = "area"
                subarea_id = "120"
                subarea_name = "BRSU_C_L0_C2_LA2"
    [state_descriptions.GO_TO_ELEVATOR]
        state_module_name = "ropod_experiment_executor.commands.goto"
        state_class_name = "GoTo"
        [state_descriptions.GO_TO_ELEVATOR.transitions]
            done = "ENTER_ELEVATOR"
            failed = "FAILED"
        [state_descriptions.GO_TO_ELEVATOR.arguments]
            timeout_s = 1200.0
    [state_descriptions.ENTER_ELEVATOR]
        state_module_name = "ropod_experiment_executor.commands.enter_elevator"
        state_class_name = "EnterElevator"
        [state_descriptions.ENTER_ELEVATOR.transitions]
            done = "DONE"
            failed = "FAILED"
        [state_descriptions.ENTER_ELEVATOR.arguments]
            area_floor = 0
            elevator_id = 121
            elevator_door_id = 196
            timeout_s = 120.0

[arguments]
    goto_action_server_name = "/ropod/goto"
    goto_progress_topic = "/ropod/goto/feedback"
    elevator_action_server_name = "/ropod/take_elevator"
    elevator_progress_topic = "/ropod/take_elevator/feedback"
