# Description: Defines a state machine for a simple area navigation experiment
# Author: Santosh Thoduka
# Email: santosh.thoduka@h-brs.de
sm_id: nav_dock_undock
states: [GO_TO, DOCK, GO_TO, UNDOCK, GO_TO]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: GO_TO
        state_module_name: ropod_experiment_executor.commands.goto
        state_class_name: GoTo
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: areas
                value:
                    -
                        area_id: '5'
                        area_name: BRSU_C_L0_C9
                        area_type: corridor
                        subarea_id: '61'
                        subarea_name: BRSU_C_L0_C9_LA1
                    -
                        area_id: '7'
                        area_name: BRSU_C_L0_C8
                        area_type: junction
                        subarea_id: '64'
                        subarea_name: BRSU_C_L0_C8_LA1
                    -
                        area_id: '2'
                        area_name: BRSU_C_L0_C11
                        area_type: corridor
                        subarea_id: '57'
                        subarea_name: BRSU_C_L0_C11_LA2
            - argument:
                name: area_floor
                value: 0
            - argument:
                name: go_to_action_topic
                value: /ropod_task_executor/GOTO
            - argument:
                name: go_to_progress_topic
                value: /task_progress/goto
            - argument:
                name: timeout_s
                value: 120.0
    - state:
        name: DOCK
        state_module_name: ropod_experiment_executor.commands.dock
        state_class_name: Dock
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: area_id
                value: MobidikArea2
            - argument:
                name: area_name
                value: orient_wp_MobidikArea2
            - argument:
                name: timeout_s
                value: 120.0
    - state:
        name: GO_TO
        state_module_name: ropod_experiment_executor.commands.goto
        state_class_name: GoTo
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: areas
                value:
                    -
                        area_id: '2'
                        area_name: BRSU_C_L0_C11
                        area_type: corridor
                        subarea_id: '56'
                        subarea_name: BRSU_C_L0_C11_LA1
                    -
                        area_id: '7'
                        area_name: BRSU_C_L0_C8
                        area_type: junction
                        subarea_id: '64'
                        subarea_name: BRSU_C_L0_C8_LA1
                    -
                        area_id: '8'
                        area_name: BRSU_C_L0_C6
                        area_type: corridor
                        subarea_id: '68'
                        subarea_name: BRSU_C_L0_C6_LA1
                    -
                        area_id: '9'
                        area_name: BRSU_C_L0_C5
                        area_type: corridor
                        subarea_id: '70'
                        subarea_name: BRSU_C_L0_C5_LA1
                    -
                        area_id: '10'
                        area_name: BRSU_C_L0_C4
                        area_type: corridor
                        subarea_id: '72'
                        subarea_name: BRSU_C_L0_C4_LA1
                    -
                        area_id: '12'
                        area_name: BRSU_C_L0_C2
                        area_type: junction
                        subarea_id: '75'
                        subarea_name: BRSU_C_L0_C2_LA1
                    -
                        area_id: '13'
                        area_name: BRSU_C_L0_C2
                        area_type: corridor
                        subarea_id: '76'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '123'
                        area_name: BRSU_C_L0_C2
                        area_type: area
                        subarea_id: '117'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '124'
                        area_name: BRSU_C_L0_C2
                        area_type: area
                        subarea_id: '118'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '126'
                        area_name: BRSU_C_L0_C2
                        area_type: area
                        subarea_id: '119'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '125'
                        area_name: BRSU_C_L0_C2
                        area_type: area
                        subarea_id: '120'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '126'
                        area_name: BRSU_C_L0_C2
                        area_type: area
                        subarea_id: '119'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '124'
                        area_name: BRSU_C_L0_C2
                        area_type: area
                        subarea_id: '118'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '123'
                        area_name: BRSU_C_L0_C2
                        area_type: area
                        subarea_id: '117'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '13'
                        area_name: BRSU_C_L0_C2
                        area_type: corridor
                        subarea_id: '77'
                        subarea_name: BRSU_C_L0_C2_LA2
                    -
                        area_id: '10'
                        area_name: BRSU_C_L0_C4
                        area_type: corridor
                        subarea_id: '71'
                        subarea_name: BRSU_C_L0_C4_LA2
                    -
                        area_id: '9'
                        area_name: BRSU_C_L0_C5
                        area_type: corridor
                        subarea_id: '69'
                        subarea_name: BRSU_C_L0_C5_LA2
                    -
                        area_id: '8'
                        area_name: BRSU_C_L0_C6
                        area_type: corridor
                        subarea_id: '67'
                        subarea_name: BRSU_C_L0_C6_LA2
                    -
                        area_id: '92'
                        area_name: BRSU_C_L0_C7
                        area_type: corridor
                        subarea_id: '65'
                        subarea_name: BRSU_C_L0_C7_LA2
                    -
                        area_id: '7'
                        area_name: BRSU_C_L0_C8
                        area_type: junction
                        subarea_id: '64'
                        subarea_name: BRSU_C_L0_C8_LA1
                    -
                        area_id: '2'
                        area_name: BRSU_C_L0_C11
                        area_type: junction
                        subarea_id: '57'
                        subarea_name: BRSU_C_L0_C11_LA2
            - argument:
                name: area_floor
                value: 0
            - argument:
                name: go_to_action_topic
                value: /ropod_task_executor/GOTO
            - argument:
                name: go_to_progress_topic
                value: /task_progress/goto
            - argument:
                name: timeout_s
                value: 120.0
    - state:
        name: UNDOCK
        state_module_name: ropod_experiment_executor.commands.undock
        state_class_name: UnDock
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: area_id
                value: MobidikArea1
            - argument:
                name: area_name
                value: orient_wp_MobidikArea1
            - argument:
                name: timeout_s
                value: 120.0
    - state:
        name: GO_TO
        state_module_name: ropod_experiment_executor.commands.goto
        state_class_name: GoTo
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: areas
                value:
                    -
                        area_id: '2'
                        area_name: BRSU_C_L0_C11
                        area_type: corridor
                        subarea_id: '56'
                        subarea_name: BRSU_C_L0_C11_LA1
                    -
                        area_id: '7'
                        area_name: BRSU_C_L0_C8
                        area_type: junction
                        subarea_id: '64'
                        subarea_name: BRSU_C_L0_C8_LA1
                    -
                        area_id: '5'
                        area_name: BRSU_C_L0_C9
                        area_type: corridor
                        subarea_id: '60'
                        subarea_name: BRSU_C_L0_C9_LA2
            - argument:
                name: area_floor
                value: 0
            - argument:
                name: go_to_action_topic
                value: /ropod_task_executor/GOTO
            - argument:
                name: go_to_progress_topic
                value: /task_progress/goto
            - argument:
                name: timeout_s
                value: 120.0
