sm_id = "nav_dock_undock"
states = ["GET_PATH_PLAN_TO_DOCKING_STATION", "GO_TO_DOCKING_STATION", "DOCK", "GET_PATH_PLAN_TO_UNDOCKING_STATION", "GO_TO_UNDOCKING_STATION", "UNDOCK", "GET_PATH_PLAN_TO_HOME", "GO_TO_HOME"]
outcomes = ["DONE", "FAILED"]

[state_descriptions]
    [state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION]
        state_module_name = "ropod_experiment_executor.commands.get_path_plan"
        state_class_name = "GetPathPlan"
        initial_state = true
        [state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.transitions]
            done = "GO_TO_DOCKING_STATION"
            failed = "FAILED"
        [state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments]
            use_planner = false
            area_floor = 0
            [[state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments.areas]]
                area_id = "5"
                area_name = "BRSU_C_L0_C9"
                area_type = "corridor"
                subarea_id = "61"
                subarea_name = "BRSU_C_L0_C9_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments.areas]]
                area_id = "7"
                area_name = "BRSU_C_L0_C8"
                area_type = "junction"
                subarea_id = "64"
                subarea_name = "BRSU_C_L0_C8_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_DOCKING_STATION.arguments.areas]]
                area_id = "2"
                area_name = "BRSU_C_L0_C11"
                area_type = "corridor"
                subarea_id = "57"
                subarea_name = "BRSU_C_L0_C11_LA2"
    [state_descriptions.GO_TO_DOCKING_STATION]
        state_module_name = "ropod_experiment_executor.commands.goto"
        state_class_name = "GoTo"
        [state_descriptions.GO_TO_DOCKING_STATION.transitions]
            done = "DOCK"
            failed = "FAILED"
        [state_descriptions.GO_TO_DOCKING_STATION.arguments]
            timeout_s = 1200.0
    [state_descriptions.DOCK]
        state_module_name = "ropod_experiment_executor.commands.dock"
        state_class_name = "Dock"
        [state_descriptions.DOCK.transitions]
            done = "GET_PATH_PLAN_TO_UNDOCKING_STATION"
            failed = "FAILED"
        [state_descriptions.DOCK.arguments]
            area_id = "2"
            area_name = "BRSU_C_L0_C11"
            sub_area_id = "56"
            sub_area_name = "BRSU_C_L0_C11_LA1"
            dock_action_server_name = "/collect_cart"
            dock_progress_topic = "/collect_cart/feedback"
            timeout_s = 240.0
    [state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION]
        state_module_name = "ropod_experiment_executor.commands.get_path_plan"
        state_class_name = "GetPathPlan"
        [state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.transitions]
            done = "GO_TO_UNDOCKING_STATION"
            failed = "FAILED"
        [state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments]
            use_planner = false
            area_floor = 0
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "2"
                area_name = "BRSU_C_L0_C11"
                area_type = "corridor"
                subarea_id = "56"
                subarea_name = "BRSU_C_L0_C11_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "7"
                area_name = "BRSU_C_L0_C8"
                area_type = "junction"
                subarea_id = "64"
                subarea_name = "BRSU_C_L0_C8_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "92"
                area_name = "BRSU_C_L0_C7"
                area_type = "corridor"
                subarea_id = "66"
                subarea_name = "BRSU_C_L0_C7_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "8"
                area_name = "BRSU_C_L0_C6"
                area_type = "corridor"
                subarea_id = "68"
                subarea_name = "BRSU_C_L0_C6_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "9"
                area_name = "BRSU_C_L0_C5"
                area_type = "corridor"
                subarea_id = "70"
                subarea_name = "BRSU_C_L0_C5_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "10"
                area_name = "BRSU_C_L0_C4"
                area_type = "corridor"
                subarea_id = "72"
                subarea_name = "BRSU_C_L0_C4_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "12"
                area_name = "BRSU_C_L0_C2"
                area_type = "junction"
                subarea_id = "75"
                subarea_name = "BRSU_C_L0_C2_LA1"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "11"
                area_name = "BRSU_C_L0_C2"
                area_type = "corridor"
                subarea_id = "73"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "116"
                area_name = "BRSU_C_L0_C2"
                area_type = "junction"
                subarea_id = "93"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "287"
                area_name = "BRSU_C_L0_C2"
                area_type = "area"
                subarea_id = "286"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "100"
                area_name = "BRSU_C_L0_C2"
                area_type = "junction"
                subarea_id = "26"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "101"
                area_name = "BRSU_C_L0_C2"
                area_type = "corridor"
                subarea_id = "27"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "103"
                area_name = "BRSU_C_L0_C2"
                area_type = "junction"
                subarea_id = "29"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "104"
                area_name = "BRSU_C_L0_C2"
                area_type = "corridor"
                subarea_id = "32"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "105"
                area_name = "BRSU_C_L0_C2"
                area_type = "corridor"
                subarea_id = "35"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "106"
                area_name = "BRSU_C_L0_C2"
                area_type = "corridor"
                subarea_id = "36"
                subarea_name = "BRSU_C_L0_C2_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "107"
                area_name = "BRSU_C_L0_C4"
                area_type = "corridor"
                subarea_id = "39"
                subarea_name = "BRSU_C_L0_C4_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "108"
                area_name = "BRSU_C_L0_C5"
                area_type = "corridor"
                subarea_id = "40"
                subarea_name = "BRSU_C_L0_C5_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "113"
                area_name = "BRSU_C_L0_C6"
                area_type = "junction"
                subarea_id = "49"
                subarea_name = "BRSU_C_L0_C6_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "112"
                area_name = "BRSU_C_L0_C7"
                area_type = "corridor"
                subarea_id = "48"
                subarea_name = "BRSU_C_L0_C7_LA2"
            [[state_descriptions.GET_PATH_PLAN_TO_UNDOCKING_STATION.arguments.areas]]
                area_id = "111"
                area_name = "BRSU_C_L0_C9"
                area_type = "corridor"
                subarea_id = "45"
                subarea_name = "BRSU_C_L0_C9_LA1"
    [state_descriptions.GO_TO_UNDOCKING_STATION]
        state_module_name = "ropod_experiment_executor.commands.goto"
        state_class_name = "GoTo"
        [state_descriptions.GO_TO_UNDOCKING_STATION.transitions]
            done = "UNDOCK"
            failed = "FAILED"
        [state_descriptions.GO_TO_UNDOCKING_STATION.arguments]
            timeout_s = 1200.0
    [state_descriptions.UNDOCK]
        state_module_name = "ropod_experiment_executor.commands.undock"
        state_class_name = "UnDock"
        [state_descriptions.UNDOCK.transitions]
            done = "DONE"
            failed = "FAILED"
        [state_descriptions.UNDOCK.arguments]
            area_id = "111"
            area_name = "BRSU_C_L0_C9"
            sub_area_id = "46"
            sub_area_name = "BRSU_C_L0_C9_LA1"
            dock_action_server_name = "/collect_cart"
            dock_progress_topic = "/collect_cart/feedback"
            timeout_s = 240.0

[arguments]
    goto_action_server_name = "/ropod/goto"
    goto_progress_topic = "/ropod/goto/feedback"
