# Description: Defines a state machine for a undocking
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: undock
states: [UNDOCK]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: UNDOCK
        state_module_name: ropod_experiment_executor.commands.undock
        state_class_name: UnDock
        transitions:
            - transition:
                name: done
                state: DONE
            - transition:
                name: failed
                state: FAILED
        arguments:
            - argument:
                name: area_id
                value: MobidikArea1
            - argument:
                name: area_name
                value: orient_wp_MobidikArea1
            - argument:
                name: timeout_s
                value: 120.0
