parent_module_name: 'ropod_experiment_executor.commands'
commands:
    - name: GO_FORWARD
      type: base_motion
      args:
          vel_x: 0.1
          vel_y: 0.0
          vel_theta: 0.0
          vel_topic: /ropod/cmd_vel
          duration: 3.0
    - name: GO_BACKWARD
      type: base_motion
      args:
          vel_x: -0.1
          vel_y: 0.0
          vel_theta: 0.0
          vel_topic: /ropod/cmd_vel
          duration: 3.0
    - name: GO_LEFT
      type: base_motion
      args:
          vel_x: 0.0
          vel_y: -0.1
          vel_theta: 0.0
          vel_topic: /ropod/cmd_vel
          duration: 3.0
    - name: GO_RIGHT
      type: base_motion
      args:
          vel_x: 0.0
          vel_y: 0.1
          vel_theta: 0.0
          vel_topic: /ropod/cmd_vel
          duration: 3.0
    - name: TURN_RIGHT
      type: base_motion
      args:
          vel_x: 0.0
          vel_y: 0.0
          vel_theta: 0.3
          vel_topic: /ropod/cmd_vel
          duration: 3.0
    - name: TURN_LEFT
      type: base_motion
      args:
          vel_x: 0.0
          vel_y: 0.0
          vel_theta: -0.3
          vel_topic: /ropod/cmd_vel
          duration: 3.0
